#!/usr/bin/env node
// Regenerates src/types.gen.ts from the JSON Schemas (the schemas are the source of truth, ADR-006).
// `--check` exits 2 when the committed file is stale.
import { readFileSync, writeFileSync } from 'node:fs';
import { compile } from 'json-schema-to-typescript';

const here = (p) => new URL(p, import.meta.url);
const STYLE = { printWidth: 100, singleQuote: true, trailingComma: 'all', endOfLine: 'lf' };

export async function generate() {
  const parts = [
    '/* Generated by packages/spec/scripts/gen-types.mjs from schema/*.schema.json. Do not edit. */\n',
  ];
  for (const [file, name] of [
    ['../schema/incubator.schema.json', 'IncubatorSpec'],
    ['../schema/discovery-turn.schema.json', 'DiscoveryTurn'],
  ]) {
    const schema = JSON.parse(readFileSync(here(file), 'utf8'));
    parts.push(
      await compile(schema, name, {
        bannerComment: '',
        style: STYLE,
        additionalProperties: false,
        unreachableDefinitions: false,
        maxItems: -1,
      }),
    );
  }
  return parts.join('\n');
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split(/[\\/]/).pop())) {
  const out = await generate();
  const target = here('../src/types.gen.ts');
  if (process.argv.includes('--check')) {
    const have = readFileSync(target, 'utf8');
    if (have !== out) {
      process.stderr.write(
        'src/types.gen.ts is stale: run node packages/spec/scripts/gen-types.mjs\n',
      );
      process.exit(2);
    }
  } else writeFileSync(target, out);
}
