/* Generated by packages/spec/scripts/gen-types.mjs from schema/*.schema.json. Do not edit. */

export type BranchName = string;
export type WorkLane =
  | 'workspace'
  | 'security'
  | 'support/existing'
  | 'testing'
  | 'infra'
  | 'enhancement/existing'
  | 'enhancement/new'
  | 'ui/fix'
  | 'ui/feature';
export type Host = string;
export type AgentId = 'claude' | 'copilot' | 'cursor';
export type ActionId = string;

/**
 * incubator.json: everything the deterministic template engine needs to render a repository.
 */
export interface IncubatorSpec {
  $schema?: string;
  /**
   * 1.0 for new and adopted projects; 1.1 adds enhancement runs (mode, existingRepo, feature targets).
   */
  incubatorVersion: '1.0' | '1.1';
  mode: 'greenfield' | 'brownfield' | 'enhancement';
  existingRepo?: ExistingRepo;
  project: Project;
  intent: Intent;
  platform: 'web' | 'service' | 'cli' | 'library' | 'wordpress-plugin' | 'wordpress-theme';
  stack: Stack;
  lanes: Lanes;
  deploy: Deploy;
  testing: Testing;
  security: Security;
  agents: Agents;
  tracker: Tracker;
  templates: Templates;
  source: Source;
  gapReport: GapItem[];
  decisions: Decision[];
}
/**
 * The repository an enhancement run changes: what was scanned, and at which commit.
 */
export interface ExistingRepo {
  ref: string;
  defaultBranch: BranchName;
  baseSha: string;
  scanHash: string;
}
export interface Project {
  name: string;
  slug: string;
  description: string;
  owner: Owner;
  visibility: 'private' | 'public' | 'internal';
}
export interface Owner {
  type: 'user' | 'org';
  login: string;
}
export interface Intent {
  narrative: string;
  /**
   * @maxItems 10
   */
  personas: string[];
  /**
   * @maxItems 20
   */
  coreFeatures: CoreFeature[];
}
export interface CoreFeature {
  id: string;
  summary: string;
  lane: WorkLane;
  /**
   * Repository-relative files or directories the change touches, resolved from the scan (enhancement runs).
   *
   * @maxItems 20
   */
  targets?: string[];
}
export interface Stack {
  pack: 'node-web' | 'wordpress' | 'python-service' | 'node-lib';
  framework:
    'fastify-react' | 'fastapi' | 'wordpress-plugin' | 'wordpress-theme' | 'typescript-lib';
  database: 'postgres' | 'mariadb' | 'none';
  auth: 'none' | 'session' | 'oauth' | 'jwt' | 'wordpress';
  packageManager: 'pnpm' | 'npm' | 'composer' | 'uv';
}
export interface Lanes {
  environments: ('local' | 'staging' | 'prod')[];
  branches: Branches;
  workLanes: WorkLane[];
}
export interface Branches {
  staging: BranchName;
  prod: BranchName;
}
export interface Deploy {
  target: 'vps-tailscale' | 'docker-host' | 'package-release';
  registry?: string;
  staging: StagingTarget;
  prod: ProdTarget;
}
export interface StagingTarget {
  host: Host;
  tailnetOnly: boolean;
}
export interface ProdTarget {
  host: Host;
}
export interface Testing {
  home: 'in-repo' | 'paired-repo';
  profiles: ('quick' | 'full' | 'chaos' | 'hardening' | 'release' | 'live')[];
  coverageThreshold: number;
  completenessThreshold: number;
  e2e: 'playwright' | 'none';
  pairedRepo?: PairedRepo;
}
export interface PairedRepo {
  name: string;
}
export interface Security {
  scanners: ('semgrep' | 'trivy' | 'gitleaks')[];
  policyGate: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  centralRig: CentralRig;
}
export interface CentralRig {
  enabled: boolean;
  repo: string;
}
export interface Agents {
  primary: AgentId;
  also: AgentId[];
  runCeilings: RunCeilings;
  deniedActions: ActionId[];
  humanOnlyActions: ActionId[];
}
export interface RunCeilings {
  turns: number;
  toolCalls: number;
  minutes: number;
  usd: number;
}
export interface Tracker {
  type: 'leantime' | 'local';
  leantime?: LeantimeConfig;
}
export interface LeantimeConfig {
  baseUrl: '' | string;
  projectId: number | null;
  statusMap?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[A-Z_]+$".
     */
    [k: string]: number;
  };
}
export interface Templates {
  packs: PackRef[];
}
export interface PackRef {
  id: string;
  version: string;
}
export interface Source {
  type: 'none' | 'github' | 'local';
  ref: string;
}
export interface GapItem {
  id: string;
  category?: string;
  status: 'present' | 'partial' | 'missing';
  evidence: string[];
  action: 'none' | 'create' | 'propose';
}
export interface Decision {
  key: string;
  question: string;
  answer: string;
  source: 'user' | 'inferred' | 'default';
}

/**
 * One reply of the discovery engine: the updated draft spec, open questions and whether it is done.
 */
export interface DiscoveryTurn {
  /**
   * A partial incubator.json. Every value the model set must have a matching decisions[] entry.
   */
  draftSpec: {};
  questions: Question[];
  done: boolean;
}
export interface Question {
  key: string;
  question: string;
  impact: number;
  /**
   * @minItems 2
   * @maxItems 4
   */
  options: [QuestionOption, QuestionOption, ...QuestionOption[]];
}
export interface QuestionOption {
  value: string;
  label: string;
  recommended: boolean;
}
